[versions]
# Android Build Gradle
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"

# Jetbrains
kotlin = "1.9.22"

# Androidx
camera = "1.3.1"
compiler = "1.5.10"
core-ktx = "1.12.0"
lifecycle = "2.7.0"
compose-bom = "2024.02.01"
espresso-core = "3.5.1"
activity-compose = "1.8.2"
androidx-test-ext-junit = "1.1.5"

# Junit
junit = "4.13.2"

# Plugins
android-gradle-plugin = "8.3.0"
sqldelight-plugin = "2.0.1"

[libraries]
# Junit
junit = { module = "junit:junit", version.ref = "junit" }

# Androidx Test
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

# Androidx Activity
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

# Androidx Core
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

# Androidx Lifecycle
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# Androidx Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling"}
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest"}

# Anroidx Camera
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
androidx-camera-video = { module = "androidx.camera:camera-video", version.ref = "camera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera" }

[bundles]
androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-runtime",
    "androidx-compose-compiler",
    "androidx-compose-material3",
    "androidx-compose-animation",
    "androidx-compose-foundation"
]
androidx-camera = [
    "androidx-camera-core",
    "androidx-camera-view",
    "androidx-camera-video",
    "androidx-camera-camera2",
    "androidx-camera-lifecycle",
    "androidx-camera-extensions"
]

[plugins]
# Jetbrains
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Android
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }

# Cashapp
cashapp-sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight-plugin" }

